# This workflow runs the unit and system tests, as well as static code analysis
# and dependecy vulnerability checks.
#
# It uses the default MySQL database included in the runner (usually ubuntu-latest).
name: "Tests and code quality"
on:
  push:
    branches:
      - "main"
      - "release/**"
  pull_request:
    branches:
      - "main"
      - "release/**"
jobs:
  linters:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint
      cancel-in-progress: true
    name: Linters
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: '3.0.4'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7 # v1.92
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: RuboCop linting
        run: |
          bundle exec rubocop --parallel

      - name: Bundler Audit
        run: |
          bundle exec bundle audit check --update

  tests:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true
    name: Tests
    runs-on: ubuntu-latest
    env:
      CI: true
      RUBY_VERSION: '3.0.4'
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7 # v1.92
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Spin up SolrCloud + Zookeeper cluster
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./solr/docker-compose.yml"
          down-flags: "--volumes"

      - name: Check Zookeeper status
        run: |
          echo "ruok" | nc localhost 2181 ; echo 

      - name: RSpec tests
        run: |
          bundle exec rspec

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          failedThreshold: 80
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.actor != 'dependabot[bot]' }}
